name: Deploy redoc pages

on:
  pull_request:
    types: [open]
    branches: develop
    paths:
      - 'spec/openapi/**.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: Install redocly/cli
        run: yarn global add @redocly/cli
      - name: Build redoc pages
        run: |
          redocly build-docs spec/openapi/openapi_admin.yml -o docs/openapi/admin/index.html
          redocly build-docs spec/openapi/openapi_user.yml -o docs/openapi/user/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
